usermail =rengaraj.k@rubixtek.com
password=123qwe

usermail_2=madhankumar.m@rubixtek.com
usermail_3=pricilla.a@rubixtek.com

tlusermail=ashwin.b@rubixtek.com
tlpassword=123qwe

managermail=hr@rubixtek.com	
managerpassword=123qwe

tenant_name=mobiletest

Holiday_month=October
Holiday_from_date=1
Holiday_To_date=1

Active_Account=abirami.s@rubixtek.com

Fromdate=2
Todate=2

multiiple_request_fromdate=8

Halfday_fromdate=9
Halfday_todate=9

multiple_fromdate=1
multiple_todate=10



weekend_fromdate=7
Weekend_todate=7

comment=approved





---------------------------------------
permission page

tenant_name_permission=preprodrubixtek
